/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface NoncesContract extends Truffle.Contract<NoncesInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<NoncesInstance>;
}

type AllEvents = never;

export interface NoncesInstance extends Truffle.ContractInstance {
  nonces(owner: string, txDetails?: Truffle.TransactionDetails): Promise<BN>;

  methods: {
    nonces(owner: string, txDetails?: Truffle.TransactionDetails): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
