/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface WeatherIdAgencyContract
  extends Truffle.Contract<WeatherIdAgencyInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<WeatherIdAgencyInstance>;
}

export interface PolicyClaimed {
  name: "PolicyClaimed";
  args: {
    id: BN;
    0: BN;
  };
}

export interface PolicyCreated {
  name: "PolicyCreated";
  args: {
    id: BN;
    0: BN;
  };
}

export interface PolicyExpired {
  name: "PolicyExpired";
  args: {
    id: BN;
    0: BN;
  };
}

export interface PolicyRetired {
  name: "PolicyRetired";
  args: {
    id: BN;
    0: BN;
  };
}

export interface PolicySettled {
  name: "PolicySettled";
  args: {
    id: BN;
    0: BN;
  };
}

type AllEvents =
  | PolicyClaimed
  | PolicyCreated
  | PolicyExpired
  | PolicyRetired
  | PolicySettled;

export interface WeatherIdAgencyInstance extends Truffle.ContractInstance {
  abiSignatureHack(
    dto: {
      latitude: number | BN | string;
      longitude: number | BN | string;
      weatherId: number | BN | string;
      weatherMain: string;
      description: string;
      temperature: number | BN | string;
      windSpeed: number | BN | string;
      windDeg: number | BN | string;
    },
    txDetails?: Truffle.TransactionDetails
  ): Promise<void>;

  claimPolicy: {
    (id: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  createPolicy: {
    (
      latitude: number | BN | string,
      longitude: number | BN | string,
      startTimestamp: number | BN | string,
      expirationTimestamp: number | BN | string,
      weatherIdThreshold: number | BN | string,
      coverage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      latitude: number | BN | string,
      longitude: number | BN | string,
      startTimestamp: number | BN | string,
      expirationTimestamp: number | BN | string,
      weatherIdThreshold: number | BN | string,
      coverage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      latitude: number | BN | string,
      longitude: number | BN | string,
      startTimestamp: number | BN | string,
      expirationTimestamp: number | BN | string,
      weatherIdThreshold: number | BN | string,
      coverage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      latitude: number | BN | string,
      longitude: number | BN | string,
      startTimestamp: number | BN | string,
      expirationTimestamp: number | BN | string,
      weatherIdThreshold: number | BN | string,
      coverage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  expirePolicy: {
    (id: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getAllPolicies(
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    {
      holder: string;
      latitude: BN;
      longitude: BN;
      startTimestamp: BN;
      expirationTimestamp: BN;
      weatherIdThreshold: BN;
      premium: BN;
      coverage: BN;
      status: BN;
      id: BN;
    }[]
  >;

  getInsurer(
    id: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  insurers(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  registeredPolicies(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: string;
    1: BN;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
    7: BN;
    8: BN;
    9: BN;
  }>;

  resolvePolicy: {
    (
      id: number | BN | string,
      proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      id: number | BN | string,
      proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      id: number | BN | string,
      proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      id: number | BN | string,
      proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  retireUnclaimedPolicy: {
    (id: number | BN | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    abiSignatureHack(
      dto: {
        latitude: number | BN | string;
        longitude: number | BN | string;
        weatherId: number | BN | string;
        weatherMain: string;
        description: string;
        temperature: number | BN | string;
        windSpeed: number | BN | string;
        windDeg: number | BN | string;
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;

    claimPolicy: {
      (
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    createPolicy: {
      (
        latitude: number | BN | string,
        longitude: number | BN | string,
        startTimestamp: number | BN | string,
        expirationTimestamp: number | BN | string,
        weatherIdThreshold: number | BN | string,
        coverage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        latitude: number | BN | string,
        longitude: number | BN | string,
        startTimestamp: number | BN | string,
        expirationTimestamp: number | BN | string,
        weatherIdThreshold: number | BN | string,
        coverage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        latitude: number | BN | string,
        longitude: number | BN | string,
        startTimestamp: number | BN | string,
        expirationTimestamp: number | BN | string,
        weatherIdThreshold: number | BN | string,
        coverage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        latitude: number | BN | string,
        longitude: number | BN | string,
        startTimestamp: number | BN | string,
        expirationTimestamp: number | BN | string,
        weatherIdThreshold: number | BN | string,
        coverage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    expirePolicy: {
      (
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getAllPolicies(
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      {
        holder: string;
        latitude: BN;
        longitude: BN;
        startTimestamp: BN;
        expirationTimestamp: BN;
        weatherIdThreshold: BN;
        premium: BN;
        coverage: BN;
        status: BN;
        id: BN;
      }[]
    >;

    getInsurer(
      id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    insurers(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    registeredPolicies(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: string;
      1: BN;
      2: BN;
      3: BN;
      4: BN;
      5: BN;
      6: BN;
      7: BN;
      8: BN;
      9: BN;
    }>;

    resolvePolicy: {
      (
        id: number | BN | string,
        proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        id: number | BN | string,
        proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        id: number | BN | string,
        proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        id: number | BN | string,
        proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    retireUnclaimedPolicy: {
      (
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        id: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
