/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ITransferEventListenerContract
  extends Truffle.Contract<ITransferEventListenerInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<ITransferEventListenerInstance>;
}

type AllEvents = never;

export interface ITransferEventListenerInstance
  extends Truffle.ContractInstance {
  collectTransferEvents: {
    (
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionHash: string;
            requiredConfirmations: number | BN | string;
            provideInput: boolean;
            listEvents: boolean;
            logIndices: (number | BN | string)[];
          };
          responseBody: {
            blockNumber: number | BN | string;
            timestamp: number | BN | string;
            sourceAddress: string;
            isDeployment: boolean;
            receivingAddress: string;
            value: number | BN | string;
            input: string;
            status: number | BN | string;
            events: {
              logIndex: number | BN | string;
              emitterAddress: string;
              topics: string[];
              data: string;
              removed: boolean;
            }[];
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionHash: string;
            requiredConfirmations: number | BN | string;
            provideInput: boolean;
            listEvents: boolean;
            logIndices: (number | BN | string)[];
          };
          responseBody: {
            blockNumber: number | BN | string;
            timestamp: number | BN | string;
            sourceAddress: string;
            isDeployment: boolean;
            receivingAddress: string;
            value: number | BN | string;
            input: string;
            status: number | BN | string;
            events: {
              logIndex: number | BN | string;
              emitterAddress: string;
              topics: string[];
              data: string;
              removed: boolean;
            }[];
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionHash: string;
            requiredConfirmations: number | BN | string;
            provideInput: boolean;
            listEvents: boolean;
            logIndices: (number | BN | string)[];
          };
          responseBody: {
            blockNumber: number | BN | string;
            timestamp: number | BN | string;
            sourceAddress: string;
            isDeployment: boolean;
            receivingAddress: string;
            value: number | BN | string;
            input: string;
            status: number | BN | string;
            events: {
              logIndex: number | BN | string;
              emitterAddress: string;
              topics: string[];
              data: string;
              removed: boolean;
            }[];
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionHash: string;
            requiredConfirmations: number | BN | string;
            provideInput: boolean;
            listEvents: boolean;
            logIndices: (number | BN | string)[];
          };
          responseBody: {
            blockNumber: number | BN | string;
            timestamp: number | BN | string;
            sourceAddress: string;
            isDeployment: boolean;
            receivingAddress: string;
            value: number | BN | string;
            input: string;
            status: number | BN | string;
            events: {
              logIndex: number | BN | string;
              emitterAddress: string;
              topics: string[];
              data: string;
              removed: boolean;
            }[];
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    collectTransferEvents: {
      (
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionHash: string;
              requiredConfirmations: number | BN | string;
              provideInput: boolean;
              listEvents: boolean;
              logIndices: (number | BN | string)[];
            };
            responseBody: {
              blockNumber: number | BN | string;
              timestamp: number | BN | string;
              sourceAddress: string;
              isDeployment: boolean;
              receivingAddress: string;
              value: number | BN | string;
              input: string;
              status: number | BN | string;
              events: {
                logIndex: number | BN | string;
                emitterAddress: string;
                topics: string[];
                data: string;
                removed: boolean;
              }[];
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionHash: string;
              requiredConfirmations: number | BN | string;
              provideInput: boolean;
              listEvents: boolean;
              logIndices: (number | BN | string)[];
            };
            responseBody: {
              blockNumber: number | BN | string;
              timestamp: number | BN | string;
              sourceAddress: string;
              isDeployment: boolean;
              receivingAddress: string;
              value: number | BN | string;
              input: string;
              status: number | BN | string;
              events: {
                logIndex: number | BN | string;
                emitterAddress: string;
                topics: string[];
                data: string;
                removed: boolean;
              }[];
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionHash: string;
              requiredConfirmations: number | BN | string;
              provideInput: boolean;
              listEvents: boolean;
              logIndices: (number | BN | string)[];
            };
            responseBody: {
              blockNumber: number | BN | string;
              timestamp: number | BN | string;
              sourceAddress: string;
              isDeployment: boolean;
              receivingAddress: string;
              value: number | BN | string;
              input: string;
              status: number | BN | string;
              events: {
                logIndex: number | BN | string;
                emitterAddress: string;
                topics: string[];
                data: string;
                removed: boolean;
              }[];
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionHash: string;
              requiredConfirmations: number | BN | string;
              provideInput: boolean;
              listEvents: boolean;
              logIndices: (number | BN | string)[];
            };
            responseBody: {
              blockNumber: number | BN | string;
              timestamp: number | BN | string;
              sourceAddress: string;
              isDeployment: boolean;
              receivingAddress: string;
              value: number | BN | string;
              input: string;
              status: number | BN | string;
              events: {
                logIndex: number | BN | string;
                emitterAddress: string;
                topics: string[];
                data: string;
                removed: boolean;
              }[];
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
