/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface GuessingGameContract
  extends Truffle.Contract<GuessingGameInstance> {
  "new"(
    maxNumber: number | BN | string,
    meta?: Truffle.TransactionDetails
  ): Promise<GuessingGameInstance>;
}

type AllEvents = never;

export interface GuessingGameInstance extends Truffle.ContractInstance {
  _generator(txDetails?: Truffle.TransactionDetails): Promise<string>;

  _maxNumber(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  guess(
    number: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  resetGame: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  methods: {
    _generator(txDetails?: Truffle.TransactionDetails): Promise<string>;

    _maxNumber(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    guess(
      number: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    resetGame: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
