/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface HelloWorldContract
  extends Truffle.Contract<HelloWorldInstance> {
  "new"(
    name: string,
    meta?: Truffle.TransactionDetails
  ): Promise<HelloWorldInstance>;
}

type AllEvents = never;

export interface HelloWorldInstance extends Truffle.ContractInstance {
  greet(txDetails?: Truffle.TransactionDetails): Promise<string>;

  greetByName(
    name: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  greetWorld(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    greet(txDetails?: Truffle.TransactionDetails): Promise<string>;

    greetByName(
      name: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    greetWorld(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
