/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface PriceAnalyticsContract
  extends Truffle.Contract<PriceAnalyticsInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<PriceAnalyticsInstance>;
}

type AllEvents = never;

export interface PriceAnalyticsInstance extends Truffle.ContractInstance {
  convertToWei(
    price: number | BN | string,
    decimals: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  provableCalculateVariance(
    priceFeeds: {
      proof: string[];
      body: {
        votingRoundId: number | BN | string;
        id: string;
        value: number | BN | string;
        turnoutBIPS: number | BN | string;
        decimals: number | BN | string;
      };
    }[],
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN[]; 1: BN; 2: BN }>;

  methods: {
    convertToWei(
      price: number | BN | string,
      decimals: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    provableCalculateVariance(
      priceFeeds: {
        proof: string[];
        body: {
          votingRoundId: number | BN | string;
          id: string;
          value: number | BN | string;
          turnoutBIPS: number | BN | string;
          decimals: number | BN | string;
        };
      }[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN[]; 1: BN; 2: BN }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
