/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface SimpleFtsoExampleContract
  extends Truffle.Contract<SimpleFtsoExampleInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<SimpleFtsoExampleInstance>;
}

type AllEvents = never;

export interface SimpleFtsoExampleInstance extends Truffle.ContractInstance {
  getCurrentTokenPriceWithDecimals(
    feedName: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN }>;

  getTokenPriceInUSDWei(
    feedName: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN }>;

  isPriceRatioHigherThan(
    token1: string,
    token2: string,
    numerator: number | BN | string,
    denominator: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: boolean }>;

  methods: {
    getCurrentTokenPriceWithDecimals(
      feedName: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN }>;

    getTokenPriceInUSDWei(
      feedName: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN }>;

    isPriceRatioHigherThan(
      token1: string,
      token2: string,
      numerator: number | BN | string,
      denominator: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: boolean }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
