/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface StarWarsCharacterListV2Contract
  extends Truffle.Contract<StarWarsCharacterListV2Instance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<StarWarsCharacterListV2Instance>;
}

type AllEvents = never;

export interface StarWarsCharacterListV2Instance
  extends Truffle.ContractInstance {
  abiSignatureHack(
    dto: {
      name: string;
      height: number | BN | string;
      mass: number | BN | string;
      numberOfMovies: number | BN | string;
      apiUid: number | BN | string;
    },
    txDetails?: Truffle.TransactionDetails
  ): Promise<void>;

  addCharacter: {
    (
      data: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      data: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      data: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      data: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  characterIds(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  characters(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: string; 1: BN; 2: BN; 3: BN }>;

  getAllCharacters(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ name: string; numberOfMovies: BN; apiUid: BN; bmi: BN }[]>;

  methods: {
    abiSignatureHack(
      dto: {
        name: string;
        height: number | BN | string;
        mass: number | BN | string;
        numberOfMovies: number | BN | string;
        apiUid: number | BN | string;
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;

    addCharacter: {
      (
        data: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        data: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        data: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        data: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    characterIds(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    characters(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: string; 1: BN; 2: BN; 3: BN }>;

    getAllCharacters(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ name: string; numberOfMovies: BN; apiUid: BN; bmi: BN }[]>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
