/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface NFTMinterContract extends Truffle.Contract<NFTMinterInstance> {
  "new"(
    _token: string,
    meta?: Truffle.TransactionDetails
  ): Promise<NFTMinterInstance>;
}

export interface NFTMinted {
  name: "NFTMinted";
  args: {
    owner: string;
    tokenId: BN;
    0: string;
    1: BN;
  };
}

type AllEvents = NFTMinted;

export interface NFTMinterInstance extends Truffle.ContractInstance {
  OWNER(txDetails?: Truffle.TransactionDetails): Promise<string>;

  USDC_CONTRACT(txDetails?: Truffle.TransactionDetails): Promise<string>;

  collectAndProcessTransferEvents: {
    (
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionHash: string;
            requiredConfirmations: number | BN | string;
            provideInput: boolean;
            listEvents: boolean;
            logIndices: (number | BN | string)[];
          };
          responseBody: {
            blockNumber: number | BN | string;
            timestamp: number | BN | string;
            sourceAddress: string;
            isDeployment: boolean;
            receivingAddress: string;
            value: number | BN | string;
            input: string;
            status: number | BN | string;
            events: {
              logIndex: number | BN | string;
              emitterAddress: string;
              topics: string[];
              data: string;
              removed: boolean;
            }[];
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionHash: string;
            requiredConfirmations: number | BN | string;
            provideInput: boolean;
            listEvents: boolean;
            logIndices: (number | BN | string)[];
          };
          responseBody: {
            blockNumber: number | BN | string;
            timestamp: number | BN | string;
            sourceAddress: string;
            isDeployment: boolean;
            receivingAddress: string;
            value: number | BN | string;
            input: string;
            status: number | BN | string;
            events: {
              logIndex: number | BN | string;
              emitterAddress: string;
              topics: string[];
              data: string;
              removed: boolean;
            }[];
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionHash: string;
            requiredConfirmations: number | BN | string;
            provideInput: boolean;
            listEvents: boolean;
            logIndices: (number | BN | string)[];
          };
          responseBody: {
            blockNumber: number | BN | string;
            timestamp: number | BN | string;
            sourceAddress: string;
            isDeployment: boolean;
            receivingAddress: string;
            value: number | BN | string;
            input: string;
            status: number | BN | string;
            events: {
              logIndex: number | BN | string;
              emitterAddress: string;
              topics: string[];
              data: string;
              removed: boolean;
            }[];
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionHash: string;
            requiredConfirmations: number | BN | string;
            provideInput: boolean;
            listEvents: boolean;
            logIndices: (number | BN | string)[];
          };
          responseBody: {
            blockNumber: number | BN | string;
            timestamp: number | BN | string;
            sourceAddress: string;
            isDeployment: boolean;
            receivingAddress: string;
            value: number | BN | string;
            input: string;
            status: number | BN | string;
            events: {
              logIndex: number | BN | string;
              emitterAddress: string;
              topics: string[];
              data: string;
              removed: boolean;
            }[];
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getTokenTransfers(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ from: string; to: string; value: BN }[]>;

  isEVMTransactionProofValid(
    transaction: {
      merkleProof: string[];
      data: {
        attestationType: string;
        sourceId: string;
        votingRound: number | BN | string;
        lowestUsedTimestamp: number | BN | string;
        requestBody: {
          transactionHash: string;
          requiredConfirmations: number | BN | string;
          provideInput: boolean;
          listEvents: boolean;
          logIndices: (number | BN | string)[];
        };
        responseBody: {
          blockNumber: number | BN | string;
          timestamp: number | BN | string;
          sourceAddress: string;
          isDeployment: boolean;
          receivingAddress: string;
          value: number | BN | string;
          input: string;
          status: number | BN | string;
          events: {
            logIndex: number | BN | string;
            emitterAddress: string;
            topics: string[];
            data: string;
            removed: boolean;
          }[];
        };
      };
    },
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  processedTransactions(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  token(txDetails?: Truffle.TransactionDetails): Promise<string>;

  tokenTransfers(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: string; 1: string; 2: BN }>;

  methods: {
    OWNER(txDetails?: Truffle.TransactionDetails): Promise<string>;

    USDC_CONTRACT(txDetails?: Truffle.TransactionDetails): Promise<string>;

    collectAndProcessTransferEvents: {
      (
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionHash: string;
              requiredConfirmations: number | BN | string;
              provideInput: boolean;
              listEvents: boolean;
              logIndices: (number | BN | string)[];
            };
            responseBody: {
              blockNumber: number | BN | string;
              timestamp: number | BN | string;
              sourceAddress: string;
              isDeployment: boolean;
              receivingAddress: string;
              value: number | BN | string;
              input: string;
              status: number | BN | string;
              events: {
                logIndex: number | BN | string;
                emitterAddress: string;
                topics: string[];
                data: string;
                removed: boolean;
              }[];
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionHash: string;
              requiredConfirmations: number | BN | string;
              provideInput: boolean;
              listEvents: boolean;
              logIndices: (number | BN | string)[];
            };
            responseBody: {
              blockNumber: number | BN | string;
              timestamp: number | BN | string;
              sourceAddress: string;
              isDeployment: boolean;
              receivingAddress: string;
              value: number | BN | string;
              input: string;
              status: number | BN | string;
              events: {
                logIndex: number | BN | string;
                emitterAddress: string;
                topics: string[];
                data: string;
                removed: boolean;
              }[];
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionHash: string;
              requiredConfirmations: number | BN | string;
              provideInput: boolean;
              listEvents: boolean;
              logIndices: (number | BN | string)[];
            };
            responseBody: {
              blockNumber: number | BN | string;
              timestamp: number | BN | string;
              sourceAddress: string;
              isDeployment: boolean;
              receivingAddress: string;
              value: number | BN | string;
              input: string;
              status: number | BN | string;
              events: {
                logIndex: number | BN | string;
                emitterAddress: string;
                topics: string[];
                data: string;
                removed: boolean;
              }[];
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionHash: string;
              requiredConfirmations: number | BN | string;
              provideInput: boolean;
              listEvents: boolean;
              logIndices: (number | BN | string)[];
            };
            responseBody: {
              blockNumber: number | BN | string;
              timestamp: number | BN | string;
              sourceAddress: string;
              isDeployment: boolean;
              receivingAddress: string;
              value: number | BN | string;
              input: string;
              status: number | BN | string;
              events: {
                logIndex: number | BN | string;
                emitterAddress: string;
                topics: string[];
                data: string;
                removed: boolean;
              }[];
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getTokenTransfers(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ from: string; to: string; value: BN }[]>;

    isEVMTransactionProofValid(
      transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionHash: string;
            requiredConfirmations: number | BN | string;
            provideInput: boolean;
            listEvents: boolean;
            logIndices: (number | BN | string)[];
          };
          responseBody: {
            blockNumber: number | BN | string;
            timestamp: number | BN | string;
            sourceAddress: string;
            isDeployment: boolean;
            receivingAddress: string;
            value: number | BN | string;
            input: string;
            status: number | BN | string;
            events: {
              logIndex: number | BN | string;
              emitterAddress: string;
              topics: string[];
              data: string;
              removed: boolean;
            }[];
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    processedTransactions(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    token(txDetails?: Truffle.TransactionDetails): Promise<string>;

    tokenTransfers(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: string; 1: string; 2: BN }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
