/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface FAssetsRedemptionQueueReaderContract
  extends Truffle.Contract<FAssetsRedemptionQueueReaderInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<FAssetsRedemptionQueueReaderInstance>;
}

type AllEvents = never;

export interface FAssetsRedemptionQueueReaderInstance
  extends Truffle.ContractInstance {
  getRedemptionQueue(
    _firstRedemptionTicketId: number | BN | string,
    _pageSize: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: { redemptionTicketId: BN; agentVault: string; ticketValueUBA: BN }[];
    1: BN;
  }>;

  methods: {
    getRedemptionQueue(
      _firstRedemptionTicketId: number | BN | string,
      _pageSize: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: { redemptionTicketId: BN; agentVault: string; ticketValueUBA: BN }[];
      1: BN;
    }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
