/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IStarWarsCharacterListV3Contract
  extends Truffle.Contract<IStarWarsCharacterListV3Instance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<IStarWarsCharacterListV3Instance>;
}

type AllEvents = never;

export interface IStarWarsCharacterListV3Instance
  extends Truffle.ContractInstance {
  addCharacter: {
    (
      data: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      data: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      data: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      data: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            url: string;
            httpMethod: string;
            headers: string;
            queryParams: string;
            body: string;
            postProcessJq: string;
            abiSignature: string;
          };
          responseBody: { abiEncodedData: string };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getAllCharacters(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ name: string; numberOfMovies: BN; apiUid: BN; bmi: BN }[]>;

  methods: {
    addCharacter: {
      (
        data: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        data: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        data: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        data: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              url: string;
              httpMethod: string;
              headers: string;
              queryParams: string;
              body: string;
              postProcessJq: string;
              abiSignature: string;
            };
            responseBody: { abiEncodedData: string };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getAllCharacters(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ name: string; numberOfMovies: BN; apiUid: BN; bmi: BN }[]>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
