/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface AssetManagerRegistryLibraryContract
  extends Truffle.Contract<AssetManagerRegistryLibraryInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<AssetManagerRegistryLibraryInstance>;
}

type AllEvents = never;

export interface AssetManagerRegistryLibraryInstance
  extends Truffle.ContractInstance {
  getFxrpAssetManager(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    getFxrpAssetManager(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
