/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface FAssetsRedeemContract
  extends Truffle.Contract<FAssetsRedeemInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<FAssetsRedeemInstance>;
}

type AllEvents = never;

export interface FAssetsRedeemInstance extends Truffle.ContractInstance {
  getFXRPAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getRedemptionRequestInfo(
    _redemptionTicketId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    redemptionRequestId: BN;
    status: BN;
    agentVault: string;
    redeemer: string;
    paymentAddress: string;
    paymentReference: string;
    valueUBA: BN;
    feeUBA: BN;
    poolFeeShareBIPS: BN;
    firstUnderlyingBlock: BN;
    lastUnderlyingBlock: BN;
    lastUnderlyingTimestamp: BN;
    timestamp: BN;
    poolSelfClose: boolean;
    transferToCoreVault: boolean;
    executor: string;
    executorFeeNatWei: BN;
  }>;

  getSettings(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN }>;

  redeem: {
    (
      _lots: number | BN | string,
      _redeemerUnderlyingAddressString: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _lots: number | BN | string,
      _redeemerUnderlyingAddressString: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      _lots: number | BN | string,
      _redeemerUnderlyingAddressString: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _lots: number | BN | string,
      _redeemerUnderlyingAddressString: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    getFXRPAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getRedemptionRequestInfo(
      _redemptionTicketId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      redemptionRequestId: BN;
      status: BN;
      agentVault: string;
      redeemer: string;
      paymentAddress: string;
      paymentReference: string;
      valueUBA: BN;
      feeUBA: BN;
      poolFeeShareBIPS: BN;
      firstUnderlyingBlock: BN;
      lastUnderlyingBlock: BN;
      lastUnderlyingTimestamp: BN;
      timestamp: BN;
      poolSelfClose: boolean;
      transferToCoreVault: boolean;
      executor: string;
      executorFeeNatWei: BN;
    }>;

    getSettings(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN }>;

    redeem: {
      (
        _lots: number | BN | string,
        _redeemerUnderlyingAddressString: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _lots: number | BN | string,
        _redeemerUnderlyingAddressString: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        _lots: number | BN | string,
        _redeemerUnderlyingAddressString: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _lots: number | BN | string,
        _redeemerUnderlyingAddressString: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
