/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface FAssetsSettingsContract
  extends Truffle.Contract<FAssetsSettingsInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<FAssetsSettingsInstance>;
}

type AllEvents = never;

export interface FAssetsSettingsInstance extends Truffle.ContractInstance {
  getLotSize(txDetails?: Truffle.TransactionDetails): Promise<{ 0: BN; 1: BN }>;

  methods: {
    getLotSize(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
