/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface SwapAndRedeemContract
  extends Truffle.Contract<SwapAndRedeemInstance> {
  "new"(
    _router: string,
    _swapPath: string[],
    meta?: Truffle.TransactionDetails
  ): Promise<SwapAndRedeemInstance>;
}

type AllEvents = never;

export interface SwapAndRedeemInstance extends Truffle.ContractInstance {
  calculateRedemptionAmountIn(
    _lots: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN }>;

  getAssetManager(txDetails?: Truffle.TransactionDetails): Promise<string>;

  router(txDetails?: Truffle.TransactionDetails): Promise<string>;

  swapAndRedeem: {
    (
      _lots: number | BN | string,
      _redeemerUnderlyingAddressString: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _lots: number | BN | string,
      _redeemerUnderlyingAddressString: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN[]; 3: BN[]; 4: BN }>;
    sendTransaction(
      _lots: number | BN | string,
      _redeemerUnderlyingAddressString: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _lots: number | BN | string,
      _redeemerUnderlyingAddressString: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  swapPath(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  token(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    calculateRedemptionAmountIn(
      _lots: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN }>;

    getAssetManager(txDetails?: Truffle.TransactionDetails): Promise<string>;

    router(txDetails?: Truffle.TransactionDetails): Promise<string>;

    swapAndRedeem: {
      (
        _lots: number | BN | string,
        _redeemerUnderlyingAddressString: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _lots: number | BN | string,
        _redeemerUnderlyingAddressString: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<{ 0: BN; 1: BN; 2: BN[]; 3: BN[]; 4: BN }>;
      sendTransaction(
        _lots: number | BN | string,
        _redeemerUnderlyingAddressString: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _lots: number | BN | string,
        _redeemerUnderlyingAddressString: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    swapPath(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    token(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
