/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from "./AccessControl";
import { IAccessControlContract } from "./IAccessControl";
import { OwnableContract } from "./Ownable";
import { IERC1155ErrorsContract } from "./IERC1155Errors";
import { IERC20ErrorsContract } from "./IERC20Errors";
import { IERC721ErrorsContract } from "./IERC721Errors";
import { IERC5267Contract } from "./IERC5267";
import { ERC20Contract } from "./ERC20";
import { ERC20BurnableContract } from "./ERC20Burnable";
import { ERC20PermitContract } from "./ERC20Permit";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC20PermitContract } from "./IERC20Permit";
import { IERC20Contract } from "./IERC20";
import { ERC721Contract } from "./ERC721";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721Contract } from "./IERC721";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { ECDSAContract } from "./ECDSA";
import { EIP712Contract } from "./EIP712";
import { MerkleProofContract } from "./MerkleProof";
import { ERC165Contract } from "./ERC165";
import { IERC165Contract } from "./IERC165";
import { SafeCastContract } from "./SafeCast";
import { NoncesContract } from "./Nonces";
import { PausableContract } from "./Pausable";
import { ReentrancyGuardContract } from "./ReentrancyGuard";
import { ShortStringsContract } from "./ShortStrings";
import { StringsContract } from "./Strings";
import { AddressUpdatableContract } from "./AddressUpdatable";
import { AddressUpdaterContract } from "./AddressUpdater";
import { IAddressValidityVerificationContract } from "./IAddressValidityVerification";
import { IBalanceDecreasingTransactionVerificationContract } from "./IBalanceDecreasingTransactionVerification";
import { IConfirmedBlockHeightExistsVerificationContract } from "./IConfirmedBlockHeightExistsVerification";
import { IEVMTransactionVerificationContract } from "./IEVMTransactionVerification";
import { IJsonApiVerificationOtherContract } from "./IJsonApiVerificationOther";
import { IPaymentVerificationContract } from "./IPaymentVerification";
import { IReferencedPaymentNonexistenceVerificationContract } from "./IReferencedPaymentNonexistenceVerification";
import { FdcVerificationContract } from "./FdcVerification";
import { GovernedBaseOldContract } from "./GovernedBaseOld";
import { GovernedOldContract } from "./GovernedOld";
import { IFdcVerificationOldContract } from "./IFdcVerificationOld";
import { IIAddressUpdatableContract } from "./IIAddressUpdatable";
import { IIAddressUpdatableContract } from "./IIAddressUpdatable";
import { IIAddressUpdaterContract } from "./IIAddressUpdater";
import { IStarWarsCharacterListV3Contract } from "./IStarWarsCharacterListV3";
import { StarWarsCharacterListV3Contract } from "./StarWarsCharacterListV3";
import { INFTMinterContract } from "./INFTMinter";
import { NFTMinterContract } from "./NFTMinter";
import { MyNFTContract } from "./MyNFT";
import { InflationCustomFeedContract } from "./InflationCustomFeed";
import { MetalPriceVerifierCustomFeedContract } from "./MetalPriceVerifierCustomFeed";
import { PriceVerifierCustomFeedContract } from "./PriceVerifierCustomFeed";
import { FAssetsRedeemContract } from "./FAssetsRedeem";
import { FAssetsSettingsContract } from "./FAssetsSettings";
import { FAssetsRedemptionQueueReaderContract } from "./FAssetsRedemptionQueueReader";
import { ISwapRouterContract } from "./ISwapRouter";
import { SwapAndRedeemContract } from "./SwapAndRedeem";
import { AddressRegistryContract } from "./AddressRegistry";
import { IAddressRegistryContract } from "./IAddressRegistry";
import { ITransferEventListenerContract } from "./ITransferEventListener";
import { TransferEventListenerContract } from "./TransferEventListener";
import { IStarWarsCharacterListContract } from "./IStarWarsCharacterList";
import { StarWarsCharacterListContract } from "./StarWarsCharacterList";
import { IPaymentRegistryContract } from "./IPaymentRegistry";
import { PaymentRegistryContract } from "./PaymentRegistry";
import { IStarWarsCharacterListV2Contract } from "./IStarWarsCharacterListV2";
import { StarWarsCharacterListV2Contract } from "./StarWarsCharacterListV2";
import { FtsoV2ConsumerContract } from "./FtsoV2Consumer";
import { GuessingGameContract } from "./GuessingGame";
import { HelloWorldContract } from "./HelloWorld";
import { PriceAnalyticsContract } from "./PriceAnalytics";
import { ProofOfReservesContract } from "./ProofOfReserves";
import { MyStablecoinContract } from "./MyStablecoin";
import { TokenStateReaderContract } from "./TokenStateReader";
import { SimpleFtsoExampleContract } from "./SimpleFtsoExample";
import { MinTempAgencyContract } from "./MinTempAgency";
import { WeatherIdAgencyContract } from "./WeatherIdAgency";
import { IICustomFeedContract } from "./IICustomFeed";
import { IDiamondLoupeContract } from "./IDiamondLoupe";
import { IIFtsoContract } from "./IIFtso";
import { FtsoV2InterfaceContract } from "./FtsoV2Interface";
import { IFtsoGenesisContract } from "./IFtsoGenesis";
import { IFtsoManagerGenesisContract } from "./IFtsoManagerGenesis";
import { IFtsoRegistryGenesisContract } from "./IFtsoRegistryGenesis";
import { IAddressValidityVerificationContract } from "./IAddressValidityVerification";
import { IAgentAlwaysAllowedMintersContract } from "./IAgentAlwaysAllowedMinters";
import { IAgentPingContract } from "./IAgentPing";
import { IAssetManagerContract } from "./IAssetManager";
import { IAssetManagerControllerContract } from "./IAssetManagerController";
import { IAssetManagerEventsContract } from "./IAssetManagerEvents";
import { IBalanceDecreasingTransactionVerificationContract } from "./IBalanceDecreasingTransactionVerification";
import { IClaimSetupManagerContract } from "./IClaimSetupManager";
import { IConfirmedBlockHeightExistsVerificationContract } from "./IConfirmedBlockHeightExistsVerification";
import { ICoreVaultClientContract } from "./ICoreVaultClient";
import { ICoreVaultClientSettingsContract } from "./ICoreVaultClientSettings";
import { IDelegationAccountContract } from "./IDelegationAccount";
import { IEntityManagerContract } from "./IEntityManager";
import { IEVMTransactionVerificationContract } from "./IEVMTransactionVerification";
import { IFastUpdateIncentiveManagerContract } from "./IFastUpdateIncentiveManager";
import { IFastUpdaterContract } from "./IFastUpdater";
import { IFastUpdatesConfigurationContract } from "./IFastUpdatesConfiguration";
import { IFdcHubContract } from "./IFdcHub";
import { IFdcInflationConfigurationsContract } from "./IFdcInflationConfigurations";
import { IFdcRequestFeeConfigurationsContract } from "./IFdcRequestFeeConfigurations";
import { IFdcVerificationContract } from "./IFdcVerification";
import { IFeeCalculatorContract } from "./IFeeCalculator";
import { IFlareAssetRegistryContract } from "./IFlareAssetRegistry";
import { IFlareContractRegistryContract } from "./IFlareContractRegistry";
import { IFlareSystemsCalculatorContract } from "./IFlareSystemsCalculator";
import { IFlareSystemsManagerContract } from "./IFlareSystemsManager";
import { IFtsoContract } from "./IFtso";
import { IFtsoFeedDecimalsContract } from "./IFtsoFeedDecimals";
import { IFtsoFeedIdConverterContract } from "./IFtsoFeedIdConverter";
import { IFtsoFeedPublisherContract } from "./IFtsoFeedPublisher";
import { IFtsoInflationConfigurationsContract } from "./IFtsoInflationConfigurations";
import { IFtsoManagerContract } from "./IFtsoManager";
import { IFtsoRegistryContract } from "./IFtsoRegistry";
import { IFtsoRewardManagerContract } from "./IFtsoRewardManager";
import { IFtsoRewardOffersManagerContract } from "./IFtsoRewardOffersManager";
import { IGenericRewardManagerContract } from "./IGenericRewardManager";
import { IGovernanceSettingsContract } from "./IGovernanceSettings";
import { IGovernanceVotePowerContract } from "./IGovernanceVotePower";
import { IIncreaseManagerContract } from "./IIncreaseManager";
import { IJsonApiVerificationContract } from "./IJsonApiVerification";
import { IPaymentVerificationContract } from "./IPaymentVerification";
import { IPChainStakeMirrorContract } from "./IPChainStakeMirror";
import { IPChainVotePowerContract } from "./IPChainVotePower";
import { IPriceSubmitterContract } from "./IPriceSubmitter";
import { IRandomProviderContract } from "./IRandomProvider";
import { IRedemptionTimeExtensionContract } from "./IRedemptionTimeExtension";
import { IReferencedPaymentNonexistenceVerificationContract } from "./IReferencedPaymentNonexistenceVerification";
import { IRelayContract } from "./IRelay";
import { IRewardManagerContract } from "./IRewardManager";
import { ISubmissionContract } from "./ISubmission";
import { IVoterRegistryContract } from "./IVoterRegistry";
import { IVoterWhitelisterContract } from "./IVoterWhitelister";
import { IVPContractEventsContract } from "./IVPContractEvents";
import { IVPTokenContract } from "./IVPToken";
import { IWeb2JsonVerificationContract } from "./IWeb2JsonVerification";
import { IWNatContract } from "./IWNat";
import { IWNatDelegationFeeContract } from "./IWNatDelegationFee";
import { ProtocolsV2InterfaceContract } from "./ProtocolsV2Interface";
import { RandomNumberV2InterfaceContract } from "./RandomNumberV2Interface";
import { RewardsV2InterfaceContract } from "./RewardsV2Interface";
import { TestFtsoV2InterfaceContract } from "./TestFtsoV2Interface";
import { IICleanableContract } from "./IICleanable";
import { IIGovernanceVotePowerContract } from "./IIGovernanceVotePower";
import { IIVPContractContract } from "./IIVPContract";
import { IIVPTokenContract } from "./IIVPToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(name: "IAccessControl"): IAccessControlContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "IERC1155Errors"): IERC1155ErrorsContract;
      require(name: "IERC20Errors"): IERC20ErrorsContract;
      require(name: "IERC721Errors"): IERC721ErrorsContract;
      require(name: "IERC5267"): IERC5267Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC20Burnable"): ERC20BurnableContract;
      require(name: "ERC20Permit"): ERC20PermitContract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC20Permit"): IERC20PermitContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "ECDSA"): ECDSAContract;
      require(name: "EIP712"): EIP712Contract;
      require(name: "MerkleProof"): MerkleProofContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "SafeCast"): SafeCastContract;
      require(name: "Nonces"): NoncesContract;
      require(name: "Pausable"): PausableContract;
      require(name: "ReentrancyGuard"): ReentrancyGuardContract;
      require(name: "ShortStrings"): ShortStringsContract;
      require(name: "Strings"): StringsContract;
      require(name: "AddressUpdatable"): AddressUpdatableContract;
      require(name: "AddressUpdater"): AddressUpdaterContract;
      require(
        name: "IAddressValidityVerification"
      ): IAddressValidityVerificationContract;
      require(
        name: "IBalanceDecreasingTransactionVerification"
      ): IBalanceDecreasingTransactionVerificationContract;
      require(
        name: "IConfirmedBlockHeightExistsVerification"
      ): IConfirmedBlockHeightExistsVerificationContract;
      require(
        name: "IEVMTransactionVerification"
      ): IEVMTransactionVerificationContract;
      require(
        name: "IJsonApiVerificationOther"
      ): IJsonApiVerificationOtherContract;
      require(name: "IPaymentVerification"): IPaymentVerificationContract;
      require(
        name: "IReferencedPaymentNonexistenceVerification"
      ): IReferencedPaymentNonexistenceVerificationContract;
      require(name: "FdcVerification"): FdcVerificationContract;
      require(name: "GovernedBaseOld"): GovernedBaseOldContract;
      require(name: "GovernedOld"): GovernedOldContract;
      require(name: "IFdcVerificationOld"): IFdcVerificationOldContract;
      require(name: "IIAddressUpdatable"): IIAddressUpdatableContract;
      require(name: "IIAddressUpdatable"): IIAddressUpdatableContract;
      require(name: "IIAddressUpdater"): IIAddressUpdaterContract;
      require(
        name: "IStarWarsCharacterListV3"
      ): IStarWarsCharacterListV3Contract;
      require(name: "StarWarsCharacterListV3"): StarWarsCharacterListV3Contract;
      require(name: "INFTMinter"): INFTMinterContract;
      require(name: "NFTMinter"): NFTMinterContract;
      require(name: "MyNFT"): MyNFTContract;
      require(name: "InflationCustomFeed"): InflationCustomFeedContract;
      require(
        name: "MetalPriceVerifierCustomFeed"
      ): MetalPriceVerifierCustomFeedContract;
      require(name: "PriceVerifierCustomFeed"): PriceVerifierCustomFeedContract;
      require(name: "FAssetsRedeem"): FAssetsRedeemContract;
      require(name: "FAssetsSettings"): FAssetsSettingsContract;
      require(
        name: "FAssetsRedemptionQueueReader"
      ): FAssetsRedemptionQueueReaderContract;
      require(name: "ISwapRouter"): ISwapRouterContract;
      require(name: "SwapAndRedeem"): SwapAndRedeemContract;
      require(name: "AddressRegistry"): AddressRegistryContract;
      require(name: "IAddressRegistry"): IAddressRegistryContract;
      require(name: "ITransferEventListener"): ITransferEventListenerContract;
      require(name: "TransferEventListener"): TransferEventListenerContract;
      require(name: "IStarWarsCharacterList"): IStarWarsCharacterListContract;
      require(name: "StarWarsCharacterList"): StarWarsCharacterListContract;
      require(name: "IPaymentRegistry"): IPaymentRegistryContract;
      require(name: "PaymentRegistry"): PaymentRegistryContract;
      require(
        name: "IStarWarsCharacterListV2"
      ): IStarWarsCharacterListV2Contract;
      require(name: "StarWarsCharacterListV2"): StarWarsCharacterListV2Contract;
      require(name: "FtsoV2Consumer"): FtsoV2ConsumerContract;
      require(name: "GuessingGame"): GuessingGameContract;
      require(name: "HelloWorld"): HelloWorldContract;
      require(name: "PriceAnalytics"): PriceAnalyticsContract;
      require(name: "ProofOfReserves"): ProofOfReservesContract;
      require(name: "MyStablecoin"): MyStablecoinContract;
      require(name: "TokenStateReader"): TokenStateReaderContract;
      require(name: "SimpleFtsoExample"): SimpleFtsoExampleContract;
      require(name: "MinTempAgency"): MinTempAgencyContract;
      require(name: "WeatherIdAgency"): WeatherIdAgencyContract;
      require(name: "IICustomFeed"): IICustomFeedContract;
      require(name: "IDiamondLoupe"): IDiamondLoupeContract;
      require(name: "IIFtso"): IIFtsoContract;
      require(name: "FtsoV2Interface"): FtsoV2InterfaceContract;
      require(name: "IFtsoGenesis"): IFtsoGenesisContract;
      require(name: "IFtsoManagerGenesis"): IFtsoManagerGenesisContract;
      require(name: "IFtsoRegistryGenesis"): IFtsoRegistryGenesisContract;
      require(
        name: "IAddressValidityVerification"
      ): IAddressValidityVerificationContract;
      require(
        name: "IAgentAlwaysAllowedMinters"
      ): IAgentAlwaysAllowedMintersContract;
      require(name: "IAgentPing"): IAgentPingContract;
      require(name: "IAssetManager"): IAssetManagerContract;
      require(name: "IAssetManagerController"): IAssetManagerControllerContract;
      require(name: "IAssetManagerEvents"): IAssetManagerEventsContract;
      require(
        name: "IBalanceDecreasingTransactionVerification"
      ): IBalanceDecreasingTransactionVerificationContract;
      require(name: "IClaimSetupManager"): IClaimSetupManagerContract;
      require(
        name: "IConfirmedBlockHeightExistsVerification"
      ): IConfirmedBlockHeightExistsVerificationContract;
      require(name: "ICoreVaultClient"): ICoreVaultClientContract;
      require(
        name: "ICoreVaultClientSettings"
      ): ICoreVaultClientSettingsContract;
      require(name: "IDelegationAccount"): IDelegationAccountContract;
      require(name: "IEntityManager"): IEntityManagerContract;
      require(
        name: "IEVMTransactionVerification"
      ): IEVMTransactionVerificationContract;
      require(
        name: "IFastUpdateIncentiveManager"
      ): IFastUpdateIncentiveManagerContract;
      require(name: "IFastUpdater"): IFastUpdaterContract;
      require(
        name: "IFastUpdatesConfiguration"
      ): IFastUpdatesConfigurationContract;
      require(name: "IFdcHub"): IFdcHubContract;
      require(
        name: "IFdcInflationConfigurations"
      ): IFdcInflationConfigurationsContract;
      require(
        name: "IFdcRequestFeeConfigurations"
      ): IFdcRequestFeeConfigurationsContract;
      require(name: "IFdcVerification"): IFdcVerificationContract;
      require(name: "IFeeCalculator"): IFeeCalculatorContract;
      require(name: "IFlareAssetRegistry"): IFlareAssetRegistryContract;
      require(name: "IFlareContractRegistry"): IFlareContractRegistryContract;
      require(name: "IFlareSystemsCalculator"): IFlareSystemsCalculatorContract;
      require(name: "IFlareSystemsManager"): IFlareSystemsManagerContract;
      require(name: "IFtso"): IFtsoContract;
      require(name: "IFtsoFeedDecimals"): IFtsoFeedDecimalsContract;
      require(name: "IFtsoFeedIdConverter"): IFtsoFeedIdConverterContract;
      require(name: "IFtsoFeedPublisher"): IFtsoFeedPublisherContract;
      require(
        name: "IFtsoInflationConfigurations"
      ): IFtsoInflationConfigurationsContract;
      require(name: "IFtsoManager"): IFtsoManagerContract;
      require(name: "IFtsoRegistry"): IFtsoRegistryContract;
      require(name: "IFtsoRewardManager"): IFtsoRewardManagerContract;
      require(
        name: "IFtsoRewardOffersManager"
      ): IFtsoRewardOffersManagerContract;
      require(name: "IGenericRewardManager"): IGenericRewardManagerContract;
      require(name: "IGovernanceSettings"): IGovernanceSettingsContract;
      require(name: "IGovernanceVotePower"): IGovernanceVotePowerContract;
      require(name: "IIncreaseManager"): IIncreaseManagerContract;
      require(name: "IJsonApiVerification"): IJsonApiVerificationContract;
      require(name: "IPaymentVerification"): IPaymentVerificationContract;
      require(name: "IPChainStakeMirror"): IPChainStakeMirrorContract;
      require(name: "IPChainVotePower"): IPChainVotePowerContract;
      require(name: "IPriceSubmitter"): IPriceSubmitterContract;
      require(name: "IRandomProvider"): IRandomProviderContract;
      require(
        name: "IRedemptionTimeExtension"
      ): IRedemptionTimeExtensionContract;
      require(
        name: "IReferencedPaymentNonexistenceVerification"
      ): IReferencedPaymentNonexistenceVerificationContract;
      require(name: "IRelay"): IRelayContract;
      require(name: "IRewardManager"): IRewardManagerContract;
      require(name: "ISubmission"): ISubmissionContract;
      require(name: "IVoterRegistry"): IVoterRegistryContract;
      require(name: "IVoterWhitelister"): IVoterWhitelisterContract;
      require(name: "IVPContractEvents"): IVPContractEventsContract;
      require(name: "IVPToken"): IVPTokenContract;
      require(name: "IWeb2JsonVerification"): IWeb2JsonVerificationContract;
      require(name: "IWNat"): IWNatContract;
      require(name: "IWNatDelegationFee"): IWNatDelegationFeeContract;
      require(name: "ProtocolsV2Interface"): ProtocolsV2InterfaceContract;
      require(name: "RandomNumberV2Interface"): RandomNumberV2InterfaceContract;
      require(name: "RewardsV2Interface"): RewardsV2InterfaceContract;
      require(name: "TestFtsoV2Interface"): TestFtsoV2InterfaceContract;
      require(name: "IICleanable"): IICleanableContract;
      require(name: "IIGovernanceVotePower"): IIGovernanceVotePowerContract;
      require(name: "IIVPContract"): IIVPContractContract;
      require(name: "IIVPToken"): IIVPTokenContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export {
  IAccessControlContract,
  IAccessControlInstance,
} from "./IAccessControl";
export { OwnableContract, OwnableInstance } from "./Ownable";
export {
  IERC1155ErrorsContract,
  IERC1155ErrorsInstance,
} from "./IERC1155Errors";
export { IERC20ErrorsContract, IERC20ErrorsInstance } from "./IERC20Errors";
export { IERC721ErrorsContract, IERC721ErrorsInstance } from "./IERC721Errors";
export { IERC5267Contract, IERC5267Instance } from "./IERC5267";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC20BurnableContract, ERC20BurnableInstance } from "./ERC20Burnable";
export { ERC20PermitContract, ERC20PermitInstance } from "./ERC20Permit";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC20PermitContract, IERC20PermitInstance } from "./IERC20Permit";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { ECDSAContract, ECDSAInstance } from "./ECDSA";
export { EIP712Contract, EIP712Instance } from "./EIP712";
export { MerkleProofContract, MerkleProofInstance } from "./MerkleProof";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { SafeCastContract, SafeCastInstance } from "./SafeCast";
export { NoncesContract, NoncesInstance } from "./Nonces";
export { PausableContract, PausableInstance } from "./Pausable";
export {
  ReentrancyGuardContract,
  ReentrancyGuardInstance,
} from "./ReentrancyGuard";
export { ShortStringsContract, ShortStringsInstance } from "./ShortStrings";
export { StringsContract, StringsInstance } from "./Strings";
export {
  AddressUpdatableContract,
  AddressUpdatableInstance,
} from "./AddressUpdatable";
export {
  AddressUpdaterContract,
  AddressUpdaterInstance,
} from "./AddressUpdater";
export {
  IAddressValidityVerificationContract,
  IAddressValidityVerificationInstance,
} from "./IAddressValidityVerification";
export {
  IBalanceDecreasingTransactionVerificationContract,
  IBalanceDecreasingTransactionVerificationInstance,
} from "./IBalanceDecreasingTransactionVerification";
export {
  IConfirmedBlockHeightExistsVerificationContract,
  IConfirmedBlockHeightExistsVerificationInstance,
} from "./IConfirmedBlockHeightExistsVerification";
export {
  IEVMTransactionVerificationContract,
  IEVMTransactionVerificationInstance,
} from "./IEVMTransactionVerification";
export {
  IJsonApiVerificationOtherContract,
  IJsonApiVerificationOtherInstance,
} from "./IJsonApiVerificationOther";
export {
  IPaymentVerificationContract,
  IPaymentVerificationInstance,
} from "./IPaymentVerification";
export {
  IReferencedPaymentNonexistenceVerificationContract,
  IReferencedPaymentNonexistenceVerificationInstance,
} from "./IReferencedPaymentNonexistenceVerification";
export {
  FdcVerificationContract,
  FdcVerificationInstance,
} from "./FdcVerification";
export {
  GovernedBaseOldContract,
  GovernedBaseOldInstance,
} from "./GovernedBaseOld";
export { GovernedOldContract, GovernedOldInstance } from "./GovernedOld";
export {
  IFdcVerificationOldContract,
  IFdcVerificationOldInstance,
} from "./IFdcVerificationOld";
export {
  IIAddressUpdatableContract,
  IIAddressUpdatableInstance,
} from "./IIAddressUpdatable";
export {
  IIAddressUpdatableContract,
  IIAddressUpdatableInstance,
} from "./IIAddressUpdatable";
export {
  IIAddressUpdaterContract,
  IIAddressUpdaterInstance,
} from "./IIAddressUpdater";
export {
  IStarWarsCharacterListV3Contract,
  IStarWarsCharacterListV3Instance,
} from "./IStarWarsCharacterListV3";
export {
  StarWarsCharacterListV3Contract,
  StarWarsCharacterListV3Instance,
} from "./StarWarsCharacterListV3";
export { INFTMinterContract, INFTMinterInstance } from "./INFTMinter";
export { NFTMinterContract, NFTMinterInstance } from "./NFTMinter";
export { MyNFTContract, MyNFTInstance } from "./MyNFT";
export {
  InflationCustomFeedContract,
  InflationCustomFeedInstance,
} from "./InflationCustomFeed";
export {
  MetalPriceVerifierCustomFeedContract,
  MetalPriceVerifierCustomFeedInstance,
} from "./MetalPriceVerifierCustomFeed";
export {
  PriceVerifierCustomFeedContract,
  PriceVerifierCustomFeedInstance,
} from "./PriceVerifierCustomFeed";
export { FAssetsRedeemContract, FAssetsRedeemInstance } from "./FAssetsRedeem";
export {
  FAssetsSettingsContract,
  FAssetsSettingsInstance,
} from "./FAssetsSettings";
export {
  FAssetsRedemptionQueueReaderContract,
  FAssetsRedemptionQueueReaderInstance,
} from "./FAssetsRedemptionQueueReader";
export { ISwapRouterContract, ISwapRouterInstance } from "./ISwapRouter";
export { SwapAndRedeemContract, SwapAndRedeemInstance } from "./SwapAndRedeem";
export {
  AddressRegistryContract,
  AddressRegistryInstance,
} from "./AddressRegistry";
export {
  IAddressRegistryContract,
  IAddressRegistryInstance,
} from "./IAddressRegistry";
export {
  ITransferEventListenerContract,
  ITransferEventListenerInstance,
} from "./ITransferEventListener";
export {
  TransferEventListenerContract,
  TransferEventListenerInstance,
} from "./TransferEventListener";
export {
  IStarWarsCharacterListContract,
  IStarWarsCharacterListInstance,
} from "./IStarWarsCharacterList";
export {
  StarWarsCharacterListContract,
  StarWarsCharacterListInstance,
} from "./StarWarsCharacterList";
export {
  IPaymentRegistryContract,
  IPaymentRegistryInstance,
} from "./IPaymentRegistry";
export {
  PaymentRegistryContract,
  PaymentRegistryInstance,
} from "./PaymentRegistry";
export {
  IStarWarsCharacterListV2Contract,
  IStarWarsCharacterListV2Instance,
} from "./IStarWarsCharacterListV2";
export {
  StarWarsCharacterListV2Contract,
  StarWarsCharacterListV2Instance,
} from "./StarWarsCharacterListV2";
export {
  FtsoV2ConsumerContract,
  FtsoV2ConsumerInstance,
} from "./FtsoV2Consumer";
export { GuessingGameContract, GuessingGameInstance } from "./GuessingGame";
export { HelloWorldContract, HelloWorldInstance } from "./HelloWorld";
export {
  PriceAnalyticsContract,
  PriceAnalyticsInstance,
} from "./PriceAnalytics";
export {
  ProofOfReservesContract,
  ProofOfReservesInstance,
} from "./ProofOfReserves";
export { MyStablecoinContract, MyStablecoinInstance } from "./MyStablecoin";
export {
  TokenStateReaderContract,
  TokenStateReaderInstance,
} from "./TokenStateReader";
export {
  SimpleFtsoExampleContract,
  SimpleFtsoExampleInstance,
} from "./SimpleFtsoExample";
export { MinTempAgencyContract, MinTempAgencyInstance } from "./MinTempAgency";
export {
  WeatherIdAgencyContract,
  WeatherIdAgencyInstance,
} from "./WeatherIdAgency";
export { IICustomFeedContract, IICustomFeedInstance } from "./IICustomFeed";
export { IDiamondLoupeContract, IDiamondLoupeInstance } from "./IDiamondLoupe";
export { IIFtsoContract, IIFtsoInstance } from "./IIFtso";
export {
  FtsoV2InterfaceContract,
  FtsoV2InterfaceInstance,
} from "./FtsoV2Interface";
export { IFtsoGenesisContract, IFtsoGenesisInstance } from "./IFtsoGenesis";
export {
  IFtsoManagerGenesisContract,
  IFtsoManagerGenesisInstance,
} from "./IFtsoManagerGenesis";
export {
  IFtsoRegistryGenesisContract,
  IFtsoRegistryGenesisInstance,
} from "./IFtsoRegistryGenesis";
export {
  IAddressValidityVerificationContract,
  IAddressValidityVerificationInstance,
} from "./IAddressValidityVerification";
export {
  IAgentAlwaysAllowedMintersContract,
  IAgentAlwaysAllowedMintersInstance,
} from "./IAgentAlwaysAllowedMinters";
export { IAgentPingContract, IAgentPingInstance } from "./IAgentPing";
export { IAssetManagerContract, IAssetManagerInstance } from "./IAssetManager";
export {
  IAssetManagerControllerContract,
  IAssetManagerControllerInstance,
} from "./IAssetManagerController";
export {
  IAssetManagerEventsContract,
  IAssetManagerEventsInstance,
} from "./IAssetManagerEvents";
export {
  IBalanceDecreasingTransactionVerificationContract,
  IBalanceDecreasingTransactionVerificationInstance,
} from "./IBalanceDecreasingTransactionVerification";
export {
  IClaimSetupManagerContract,
  IClaimSetupManagerInstance,
} from "./IClaimSetupManager";
export {
  IConfirmedBlockHeightExistsVerificationContract,
  IConfirmedBlockHeightExistsVerificationInstance,
} from "./IConfirmedBlockHeightExistsVerification";
export {
  ICoreVaultClientContract,
  ICoreVaultClientInstance,
} from "./ICoreVaultClient";
export {
  ICoreVaultClientSettingsContract,
  ICoreVaultClientSettingsInstance,
} from "./ICoreVaultClientSettings";
export {
  IDelegationAccountContract,
  IDelegationAccountInstance,
} from "./IDelegationAccount";
export {
  IEntityManagerContract,
  IEntityManagerInstance,
} from "./IEntityManager";
export {
  IEVMTransactionVerificationContract,
  IEVMTransactionVerificationInstance,
} from "./IEVMTransactionVerification";
export {
  IFastUpdateIncentiveManagerContract,
  IFastUpdateIncentiveManagerInstance,
} from "./IFastUpdateIncentiveManager";
export { IFastUpdaterContract, IFastUpdaterInstance } from "./IFastUpdater";
export {
  IFastUpdatesConfigurationContract,
  IFastUpdatesConfigurationInstance,
} from "./IFastUpdatesConfiguration";
export { IFdcHubContract, IFdcHubInstance } from "./IFdcHub";
export {
  IFdcInflationConfigurationsContract,
  IFdcInflationConfigurationsInstance,
} from "./IFdcInflationConfigurations";
export {
  IFdcRequestFeeConfigurationsContract,
  IFdcRequestFeeConfigurationsInstance,
} from "./IFdcRequestFeeConfigurations";
export {
  IFdcVerificationContract,
  IFdcVerificationInstance,
} from "./IFdcVerification";
export {
  IFeeCalculatorContract,
  IFeeCalculatorInstance,
} from "./IFeeCalculator";
export {
  IFlareAssetRegistryContract,
  IFlareAssetRegistryInstance,
} from "./IFlareAssetRegistry";
export {
  IFlareContractRegistryContract,
  IFlareContractRegistryInstance,
} from "./IFlareContractRegistry";
export {
  IFlareSystemsCalculatorContract,
  IFlareSystemsCalculatorInstance,
} from "./IFlareSystemsCalculator";
export {
  IFlareSystemsManagerContract,
  IFlareSystemsManagerInstance,
} from "./IFlareSystemsManager";
export { IFtsoContract, IFtsoInstance } from "./IFtso";
export {
  IFtsoFeedDecimalsContract,
  IFtsoFeedDecimalsInstance,
} from "./IFtsoFeedDecimals";
export {
  IFtsoFeedIdConverterContract,
  IFtsoFeedIdConverterInstance,
} from "./IFtsoFeedIdConverter";
export {
  IFtsoFeedPublisherContract,
  IFtsoFeedPublisherInstance,
} from "./IFtsoFeedPublisher";
export {
  IFtsoInflationConfigurationsContract,
  IFtsoInflationConfigurationsInstance,
} from "./IFtsoInflationConfigurations";
export { IFtsoManagerContract, IFtsoManagerInstance } from "./IFtsoManager";
export { IFtsoRegistryContract, IFtsoRegistryInstance } from "./IFtsoRegistry";
export {
  IFtsoRewardManagerContract,
  IFtsoRewardManagerInstance,
} from "./IFtsoRewardManager";
export {
  IFtsoRewardOffersManagerContract,
  IFtsoRewardOffersManagerInstance,
} from "./IFtsoRewardOffersManager";
export {
  IGenericRewardManagerContract,
  IGenericRewardManagerInstance,
} from "./IGenericRewardManager";
export {
  IGovernanceSettingsContract,
  IGovernanceSettingsInstance,
} from "./IGovernanceSettings";
export {
  IGovernanceVotePowerContract,
  IGovernanceVotePowerInstance,
} from "./IGovernanceVotePower";
export {
  IIncreaseManagerContract,
  IIncreaseManagerInstance,
} from "./IIncreaseManager";
export {
  IJsonApiVerificationContract,
  IJsonApiVerificationInstance,
} from "./IJsonApiVerification";
export {
  IPaymentVerificationContract,
  IPaymentVerificationInstance,
} from "./IPaymentVerification";
export {
  IPChainStakeMirrorContract,
  IPChainStakeMirrorInstance,
} from "./IPChainStakeMirror";
export {
  IPChainVotePowerContract,
  IPChainVotePowerInstance,
} from "./IPChainVotePower";
export {
  IPriceSubmitterContract,
  IPriceSubmitterInstance,
} from "./IPriceSubmitter";
export {
  IRandomProviderContract,
  IRandomProviderInstance,
} from "./IRandomProvider";
export {
  IRedemptionTimeExtensionContract,
  IRedemptionTimeExtensionInstance,
} from "./IRedemptionTimeExtension";
export {
  IReferencedPaymentNonexistenceVerificationContract,
  IReferencedPaymentNonexistenceVerificationInstance,
} from "./IReferencedPaymentNonexistenceVerification";
export { IRelayContract, IRelayInstance } from "./IRelay";
export {
  IRewardManagerContract,
  IRewardManagerInstance,
} from "./IRewardManager";
export { ISubmissionContract, ISubmissionInstance } from "./ISubmission";
export {
  IVoterRegistryContract,
  IVoterRegistryInstance,
} from "./IVoterRegistry";
export {
  IVoterWhitelisterContract,
  IVoterWhitelisterInstance,
} from "./IVoterWhitelister";
export {
  IVPContractEventsContract,
  IVPContractEventsInstance,
} from "./IVPContractEvents";
export { IVPTokenContract, IVPTokenInstance } from "./IVPToken";
export {
  IWeb2JsonVerificationContract,
  IWeb2JsonVerificationInstance,
} from "./IWeb2JsonVerification";
export { IWNatContract, IWNatInstance } from "./IWNat";
export {
  IWNatDelegationFeeContract,
  IWNatDelegationFeeInstance,
} from "./IWNatDelegationFee";
export {
  ProtocolsV2InterfaceContract,
  ProtocolsV2InterfaceInstance,
} from "./ProtocolsV2Interface";
export {
  RandomNumberV2InterfaceContract,
  RandomNumberV2InterfaceInstance,
} from "./RandomNumberV2Interface";
export {
  RewardsV2InterfaceContract,
  RewardsV2InterfaceInstance,
} from "./RewardsV2Interface";
export {
  TestFtsoV2InterfaceContract,
  TestFtsoV2InterfaceInstance,
} from "./TestFtsoV2Interface";
export { IICleanableContract, IICleanableInstance } from "./IICleanable";
export {
  IIGovernanceVotePowerContract,
  IIGovernanceVotePowerInstance,
} from "./IIGovernanceVotePower";
export { IIVPContractContract, IIVPContractInstance } from "./IIVPContract";
export { IIVPTokenContract, IIVPTokenInstance } from "./IIVPToken";
